name: build (push)

on:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::${{ github.sha }}

  build-operator:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: dockerregistry-operator
      dockerfile: components/operator/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}
  build-registry-init:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: registry-init
      dockerfile: components/registry-init/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}


# templates:
#  - from: generic.tmpl
#    render:
#      - to: ../../prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
#        localSets:
#          job_branches:
#            branches:
#              - "^main$"
#              - "^release-*"
#          skip_if_only_changed_documentation:
#            skip_if_only_changed: '^docs/|^examples/'
#        jobConfigs:
#          - repoName: kyma-project/docker-registry
#            jobs:
  #              - jobConfig:
  #                  name: post-docker-registry-operator-build
  #                  image: "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240709-b6c3d189"
  #                  annotations:
  #                    owner: otters
  #                    description: build docker-registry operator
  #                  labels:
  #                    preset-image-builder-ado-token: "true"
  #                  command: /image-builder
  #                  args:
  #                    - --name=dockerregistry-operator
  #                    - --config=/config/kaniko-build-config.yaml
  #                    - --context=.
  #                    - --dockerfile=components/operator/Dockerfile
  #                    - --tag=$(PULL_BASE_SHA)
  #                    - --tag=$(PULL_BASE_REF)
  #                    - --build-in-ado=true
  #                inheritedConfigs:
  #                  global:
  #                    - jobConfig_postsubmit
  #                    - image-builder-buildkit
  #                  local:
  #                    - job_branches
  #                    - skip_if_only_changed_documentation
  #              - jobConfig:
  #                  name: post-registry-init-build
  #                  image: "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240709-b6c3d189"
  #                  annotations:
  #                    owner: otters
  #                    description: registry-init image build
  #                  labels:
  #                    preset-image-builder-ado-token: "true"
  #                  command: /image-builder
  #                  args:
  #                    - --name=registry-init
  #                    - --config=/config/kaniko-build-config.yaml
  #                    - --context=.
  #                    - --dockerfile=components/registry-init/Dockerfile
  #                    - --tag=$(PULL_BASE_SHA)
  #                    - --tag=$(PULL_BASE_REF)
  #                    - --build-in-ado=true
  #                inheritedConfigs:
  #                  global:
  #                    - jobConfig_postsubmit
  #                    - image-builder-buildkit
  #                  local:
  #                    - job_branches
  #                    - skip_if_only_changed_documentation
#      - to: ../../prow/jobs/kyma-project/docker-registry/docker-registry-release.yaml
#        localSets:
#          release_image_build:
#            labels:
#              preset-image-builder-ado-token: "true"
#            always_run: true
#            branches:
#              - ^v?\d+\.\d+\.\d+(?:-.*)?$ #Watches for new Tag
#        jobConfigs:
#          - repoName: kyma-project/docker-registry
#            jobs:
#              - jobConfig:
#                  name: release-docker-registry-operator-build
#                  image: "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240709-b6c3d189"
#                  annotations:
#                    owner: otters
#                    description: Job to build docker-registry operator for a release.
#                  command: /image-builder
#                  args:
#                    - --name=dockerregistry-operator
#                    - --config=/config/kaniko-build-config.yaml
#                    - --context=.
#                    - --dockerfile=components/operator/Dockerfile
#                    - --tag=$(PULL_BASE_REF)
#                    - --build-in-ado=true
#                inheritedConfigs:
#                  global:
#                    - jobConfig_postsubmit
#                    - image-builder-buildkit
#                  local:
#                    - release_image_build
#              - jobConfig:
#                  name: release-registry-init-build
#                  image: "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240709-b6c3d189"
#                  annotations:
#                    owner: otters
#                    description: Job to build registry-init for a release.
#                  command: /image-builder
#                  args:
#                    - --name=registry-init
#                    - --config=/config/kaniko-build-config.yaml
#                    - --context=.
#                    - --dockerfile=components/registry-init/Dockerfile
#                    - --tag=$(PULL_BASE_REF)
#                    - --build-in-ado=true
#                inheritedConfigs:
#                  global:
#                    - jobConfig_postsubmit
#                    - image-builder-buildkit
#                  local:
#                    - release_image_build