name: build (pull)

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-operator:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: dockerregistry-operator
      dockerfile: components/operator/Dockerfile
  build-registry-init:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: registry-init
      dockerfile: components/registry-init/Dockerfile


# templates:
#  - from: generic.tmpl
#    render:
#      - to: ../../prow/jobs/kyma-project/docker-registry/docker-registry-build-operator.yaml
#        localSets:
#          job_branches:
#            branches:
#              - "^main$"
#              - "^release-*"
#          skip_if_only_changed_documentation:
#            skip_if_only_changed: '^docs/|^examples/'
#        jobConfigs:
#          - repoName: kyma-project/docker-registry
#            jobs:
  #              - jobConfig:
  #                  name: pre-docker-registry-operator-build
  #                  image: "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240709-b6c3d189"
  #                  annotations:
  #                    owner: otters
  #                    description: docker-registry operator image build
  #                  labels:
  #                    preset-image-builder-ado-token: "true"
  #                  command: /image-builder
  #                  args:
  #                    - --name=dockerregistry-operator
  #                    - --config=/config/kaniko-build-config.yaml
  #                    - --context=.
  #                    - --dockerfile=components/operator/Dockerfile
  #                    - --build-in-ado=true
  #                inheritedConfigs:
  #                  global:
  #                    - jobConfig_presubmit
  #                    - image-builder-buildkit
  #                  local:
  #                    - job_branches
  #                    - skip_if_only_changed_documentation
  #              - jobConfig:
  #                  name: pre-registry-init-build
  #                  image: "europe-docker.pkg.dev/kyma-project/prod/image-builder:v20240709-b6c3d189"
  #                  annotations:
  #                    owner: otters
  #                    description: registry-init image build
  #                  labels:
  #                    preset-image-builder-ado-token: "true"
  #                  command: /image-builder
  #                  args:
  #                    - --name=registry-init
  #                    - --config=/config/kaniko-build-config.yaml
  #                    - --context=.
  #                    - --dockerfile=components/registry-init/Dockerfile
  #                    - --build-in-ado=true
  #                inheritedConfigs:
  #                  global:
  #                    - jobConfig_presubmit
  #                    - image-builder-buildkit
  #                  local:
  #                    - job_branches
  #                    - skip_if_only_changed_documentation
