name: build (push)

on:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: echo ::set-output name=TAG::${{ github.sha }}

  build-operator:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: dockerregistry-operator
      dockerfile: components/operator/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}
  build-registry-init:
    needs: compute-tag
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: registry-init
      dockerfile: components/registry-init/Dockerfile
      tags: ${{ needs.compute-tag.outputs.tag }}
