name: operator verify

on:
  push:
    branches: [ "main", "release-*" ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]

jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: 'components/operator'

  unit-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - name: run test
        run: make -C components/operator test

  operator-integration-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rebase
      - name: run integration test (pre)
        if: github.event_name == 'pull_request'
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/dockerregistry-operator:PR-${{ github.event.number }}
      - name: run integration test (post)
        if: github.event_name == 'push'
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:${{ github.sha }}
      - uses: ./.github/actions/collect-cluster-info

#TODO: after the first release bring this test back with deploy-release target
#  operator-upgrade-test:
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/setup-go
#      - uses: ./.github/actions/create-single-cluster
#      - name: upgrade test
#        run: |
#          make -C components/operator deploy-release
#          make -C tests/operator test
#          make -C components/operator deploy
#          make -C tests/operator test
#        env:
#          IMG: europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:${{ github.sha }}
#      - uses: ./.github/actions/collect-cluster-info

  gardener-integration-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - name: save service-account
        shell: bash
        run: 'echo "$GARDENER_SA" > /tmp/gardener-sa.yaml'
        env:
          GARDENER_SA: ${{ secrets.GARDENER_SA }}
      - name: provision gardener
        run: make -C hack provision-gardener
        env:
          GARDENER_SECRET_NAME: ${{ secrets.GARDENER_SECRET_NAME }}
          GARDENER_PROJECT: ${{ secrets.GARDENER_PROJECT }}
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:${{ github.sha }}
      - name: deprovision gardener
        if: ${{ always() }}
        run: make -C hack deprovision-gardener
        env:
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml